//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELibary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeThi
    {
        public int Id { get; set; }
        public string LoaiFile { get; set; }
        public string TenDeThi { get; set; }
        public string MonHoc { get; set; }
        public string NguoiTao { get; set; }
        public string HinhThuc { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> ThoiLuong { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayThi { get; set; }
        public string TinhTrang { get; set; }
        public string NguoiPheDuyet { get; set; }
        public string GhiChu { get; set; }
    }
}
