//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELibary.Models
{
    using System;
    using System.Collections.Generic;
    public partial class HeThongThuVien
    {
        public int Id { get; set; }
        public string MaTruong { get; set; }
        public string TenTruong { get; set; }
        public string LoaiTruong { get; set; }
        public string HieuTruong { get; set; }
        public string Website { get; set; }
        public string TenThuVien { get; set; }
        public string DiaChiTruyCap { get; set; }
        public string SĐT { get; set; }
        public string Email { get; set; }
        public string NgonNgu { get; set; }
        public string NienKhoa { get; set; }
    }
}
