//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELibary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int Id { get; set; }
        public string TenVaiTro { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> MonHoc { get; set; }
        public Nullable<int> TepRiengTu { get; set; }
        public Nullable<int> TaiNguyen { get; set; }
        public Nullable<int> De { get; set; }
        public Nullable<int> ThongBao { get; set; }
        public Nullable<int> PhanQuyen { get; set; }
        public Nullable<int> NguoiDung { get; set; }
    }
}
