//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELibary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiLieu
    {
        public int Id { get; set; }
        public string TenTaiLieu { get; set; }
        public string MonHoc { get; set; }
        public string PhanLoai { get; set; }
        public string NguoiTao { get; set; }
        public string NguoiPheDuyet { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public string TinhTrang { get; set; }
        public string GhiChu { get; set; }
    }
}
