//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELibary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TepRieng
    {
        public int Id { get; set; }
        public string TheLoai { get; set; }
        public string TenTep { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<System.DateTime> NgaySuaLanCuoi { get; set; }
        public Nullable<double> KichThuoc { get; set; }
    }
}
